package week10.corba;

/**
* week10/corba/FileTransferHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ftp.idl
* Tuesday, August 28, 2012 2:24:38 AM GMT+08:00
*/

public final class FileTransferHolder implements org.omg.CORBA.portable.Streamable
{
  public week10.corba.FileTransfer value = null;

  public FileTransferHolder ()
  {
  }

  public FileTransferHolder (week10.corba.FileTransfer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = week10.corba.FileTransferHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    week10.corba.FileTransferHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return week10.corba.FileTransferHelper.type ();
  }

}
