package week10.corba;


/**
* week10/corba/FileTransferHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ftp.idl
* Tuesday, August 28, 2012 2:24:38 AM GMT+08:00
*/

abstract public class FileTransferHelper
{
  private static String  _id = "IDL:week10/corba/FileTransfer:1.0";

  public static void insert (org.omg.CORBA.Any a, week10.corba.FileTransfer that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static week10.corba.FileTransfer extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (week10.corba.FileTransferHelper.id (), "FileTransfer");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static week10.corba.FileTransfer read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_FileTransferStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, week10.corba.FileTransfer value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static week10.corba.FileTransfer narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof week10.corba.FileTransfer)
      return (week10.corba.FileTransfer)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      week10.corba._FileTransferStub stub = new week10.corba._FileTransferStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static week10.corba.FileTransfer unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof week10.corba.FileTransfer)
      return (week10.corba.FileTransfer)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      week10.corba._FileTransferStub stub = new week10.corba._FileTransferStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
