package week10.corba;


/**
* week10/corba/FileTransferPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ftp.idl
* Tuesday, August 28, 2012 2:24:38 AM GMT+08:00
*/

public abstract class FileTransferPOA extends org.omg.PortableServer.Servant
 implements week10.corba.FileTransferOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("chdir", new java.lang.Integer (0));
    _methods.put ("dir", new java.lang.Integer (1));
    _methods.put ("getdir", new java.lang.Integer (2));
    _methods.put ("get", new java.lang.Integer (3));
    _methods.put ("quit", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // week10/corba/FileTransfer/chdir
       {
         String dir = in.read_string ();
         boolean $result = false;
         $result = this.chdir (dir);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // week10/corba/FileTransfer/dir
       {
         String $result[] = null;
         $result = this.dir ();
         out = $rh.createReply();
         week10.corba.string_seqHelper.write (out, $result);
         break;
       }

       case 2:  // week10/corba/FileTransfer/getdir
       {
         String $result = null;
         $result = this.getdir ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // week10/corba/FileTransfer/get
       {
         String filename = in.read_string ();
         String $result = null;
         $result = this.get (filename);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // week10/corba/FileTransfer/quit
       {
         this.quit ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:week10/corba/FileTransfer:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public FileTransfer _this() 
  {
    return FileTransferHelper.narrow(
    super._this_object());
  }

  public FileTransfer _this(org.omg.CORBA.ORB orb) 
  {
    return FileTransferHelper.narrow(
    super._this_object(orb));
  }


} // class FileTransferPOA
