package week10.corba;


/**
* week10/corba/string_seqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ftp.idl
* Tuesday, August 28, 2012 2:24:38 AM GMT+08:00
*/

public final class string_seqHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public string_seqHolder ()
  {
  }

  public string_seqHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = week10.corba.string_seqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    week10.corba.string_seqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return week10.corba.string_seqHelper.type ();
  }

}
